name: tailwind_palette
description: A package that contains Tailwind CSS color palette. Package is inspired by https://tailwindcss.com/docs/customizing-colors. Also utilizes extension methods to make it easier to use.
version: 0.0.4
# author: Mustafa Demir <codingwithmustafa@icloud.com>
homepage: https://www.twitter.com/codewithmustafa
repository: https://github.com/codewithmustafa/fl_tailwindcss_colors/tree/main
issue_tracker: https://github.com/codewithmustafa/fl_tailwindcss_colors/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0

flutter:
