name: fl_tailwindcss_colors
description: A package that contains Tailwind CSS color palette.
version: 0.0.1
# author: Mustafa Demir <codingwithmustafa@icloud.com>
homepage: https://www.twitter.com/codewithmustafa

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
